### ISSUE TITLE
components not found

### ISSUE THREAD

**Issue by EmePin** [vazquezville/duolingo-clone-rn#1]
import WordList from "../../components/WordList/WordList";
import * as Progress from "react-native-progress";
import TalkingBallon from "../../components/TalkingBallon/TalkingBallon";
import Footer from "../../components/Footer";
import Word from "../../components/Word";
import Heart from "../../components/Heart";

those components are not found in the folders

**Comment by vazquezville** [comment]
In what component is it happening to you? I assume that you have made changes to various components, double check the routes you have modified

**Comment by EmePin** [comment]
import TalkingBallon from "../../components/TalkingBallon/TalkingBallon"; 
but this doesn't appears

**Comment by vazquezville** [comment]
It doesn't appears because there's not any component called like that. I'm assuming you want to import this new component "TalkingBallon" into somewhere in your app. once again, double check your routes when doing so.

In addition, this isn't an issue with the repo, it's related to your fork and your debug. I can help you with that, but you need to be more specific and provide me with more context and your project structure

**Comment by vazquezville** [comment]
I'm closing the issue since it has been several weeks and didn't get any feedback, good luck and don't hesitate to reach me out!
